### ISSUE TITLE
Add groups support

### ISSUE THREAD

**Issue by KalininN** [KalininN/theschedule#15]
Assign users to different studying groups, e.g. 'NNSU ASGAP 1st course' and so on

**Comment by KalininN** [comment]
Also group them by university

**Comment by KalininN** [comment]
So I think we should:
1. add universities to links: e.g. /nnsu/asgap/1/schedule
It can be done in one handler, see main.py and handlers in thehat
2. Add some group identifier in DefaultPair and ScheduledPair. I think we should use some hash maybe. (Or set group as parent? What else?)
3. Make some landing pages: choose university, choose group, etc
4. Add cookies support: user that have already chose university, should be redirected on right page from '/'

**Comment by KalininN** [comment]
We also have to manage admins in a different way

**Comment by fmlokt** [comment]
Closed in 2a69e2d
