### ISSUE TITLE
Add notifications about replacement

### ISSUE THREAD

**Issue by KalininN** [KalininN/theschedule#46]

**Comment by KalininN** [comment]
The problem is we don't mark  cancelled pairs in any way, that's why such changes are not send.

**Comment by KalininN** [comment]
Maybe we can add a 'cancelled' tag to pair, and treat it like a somewhat change.

**Comment by Unabsolutely** [comment]
A bot sends the list of these notifications unsorted chronologically.

**Comment by KalininN** [comment]
Seems done
